### PR TITLE
Bootanimation.zip

### PR DESCRIPTION
**Pull request by oumno**
Created a bootanimation for GrapheneOS.
This needs testing as I followed (outdated?) instructions from here https://forum.xda-developers.com/showthread.php?t=1096068. I was unable to get this working - I could push bootanimation to test device but could not verify it on the actual device. Not sure if instructions are for an older version of Android. 
I can provide any source file for the animation as well if anyone else wants to give this a try.

### CODE REVIEW

**Comment by charlesctr** [comment]
Hey,
Can you share the file ? Or link a video/gif to show the boot animation ?

**Comment by oumno** [comment]
> Hey,
> Can you share the file ? Or link a video/gif to show the boot animation ?

Here's a .gif of the PNG sequence that is in the .zip attachment. 

Graphene

**Comment by charlesctr** [comment]
> > Hey,
> > Can you share the file ? Or link a video/gif to show the boot animation ?
> 
> Here's a .gif of the PNG sequence that is in the .zip attachment.
> 
> Graphene

Nice one ! Let's see if the community likes it, even if it's not a priority in the development of GrapheneOS it's still a nice ressource ! Good work :)

**Comment by renlord** [comment]
can you create a PR in the branding repo instead of here.

**Pull request closed without merging**
